adaptlearning/adapt-contrib-matching

js/adapt-contrib-matching.js

due to a missing underscore. also refactored the randomisation code out into a separate method for clarity

fixes issue #56 where items were not being randomised

---

less/matching.less

Amended CSS for use with version 2 theme
Added disabled text colour state
Added cross browser default styling override for select elements

CSS theme update

---

bower.json
package.json
properties.schema

Updated mathing to matching

---

js/adapt-contrib-matching.js

This Store the user answer index, which is accurate when the component is set to randomise.

Issue with storing the user answer when randomised

---

js/adapt-contrib-matching.js

Fix the following issue: When component is randomised, answer a matching question correctly, close the course, reopen the course, you will find the matching question is set a incorrect.

Fix issue #82 #83 when randomised

---

bower.json
properties.schema

This was causing an inconsistency with other core question plugins in the authoring tool.

Resolves #1548, added missing _canShowFeedback property

---

js/adapt-contrib-matching.js
libraries/select2.js

https://github.com/adaptlearning/adapt_framework/issues/1543

issue/1543: moved dropdown into select2 element

---

less/matching.less

whilst maintaining IE8 compatibility

fixes issue with error highlighting in Firefox

---

README.md
bower.json
example.json
js/adapt-contrib-matching.js
properties.schema

resolves https://github.com/adaptlearning/adapt_framework/issues/1965
also general tidy up/update of code

adds a _shouldResetAllAnswers option

---

properties.schema
templates/matching.hbs

[#2075](https://github.com/adaptlearning/adapt_framework/issues/2075)
* Removed a11y_text
[#2084](https://github.com/adaptlearning/adapt_framework/issues/2084)
* Removed component description
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.

accessibility: fixes issue/#2075 and issue/#2084

---

js/matchingView.js

fixes https://github.com/adaptlearning/adapt_framework/issues/2316

#2316 change to allow html tags to be rendered within the component.

---

example.json
js/adapt-contrib-matching.js
js/dropdown.js
js/dropdownOption.js
js/matchingModel.js
js/matchingView.js
less/dropdown.less
less/matching.less
templates/matching.hbs
templates/partials/dropdown.hbs

Matching converted to use 2 spaces for indentation.

update to use 2 spaces for indentation

---

README.md
bower.json
less/matching.less

https://github.com/adaptlearning/adapt_framework/issues/2618

Removing the background-color setting of .matching-component ul

---

bower.json
js/matchingView.js
templates/partials/dropdown.hbs

[#2753](https://github.com/adaptlearning/adapt_framework/issues/2753)
* Switched from global remove to contentObject remove event
* Made sure dropdown lists are hidden on render, causes a jump otherwise
* Updated framework dependency

issue/2753 Switched from global remove to contentObject remove event (v5.5.0)

---

js/matchingModel.js

[#2812](https://github.com/adaptlearning/adapt_framework/issues/2812)
* Added checks for can submit in relevant places
Requires framework pr [#2820](https://github.com/adaptlearning/adapt_framework/pull/2820)

issue/2812 Disable submit button before selection

---

less/dropdown.less
less/matching.less

Related issue: https://github.com/adaptlearning/adapt_framework/issues/2891

Less tidy up

---

js/dropdownOption.js
js/matchingModel.js

fixes https://github.com/adaptlearning/adapt_framework/issues/2922

fix for 'correct answer' button not being enabled on resume

---

js/matchingModel.js
properties.schema

part of https://github.com/adaptlearning/adapt_framework/issues/2942

add support for correct/user answer text for screenreaders

---

README.md
bower.json
js/matchingView.js
package.json

Deals with issue [3154](https://github.com/adaptlearning/adapt_framework/issues/3154)

Declaring dropdowns as an empty array on initialisation

---

js/dropdown.js
js/matchingModel.js

fixes https://github.com/adaptlearning/adapt_framework/issues/2464
* Keyboard up and down arrows crashing when deselecting last option
* `listbox` should always have an active item otherwise it requires another click

issue/2464 Automatically focus on first item

---

bower.json
js/matchingView.js

Fix randomisation bug

---

js/matchingView.js
less/dropdown.less
less/matching.less
templates/matching.hbs
templates/partials/dropdown.hbs

Resolves https://github.com/adaptlearning/adapt-contrib-matching/issues/139
* Converted matching naming so each item is treated as a block within BEM

BEM naming corrections

---

bower.json
templates/matching.jsx

https://github.com/adaptlearning/adapt-contrib-matching/issues/145

Marking is being shown when it shouldnt be shown

---

bower.json
js/adapt-contrib-matching.js

requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Switched to components.register from Adapt.register

issue/2799 Remove redundant behaviour

---

less/dropdown.less
templates/matchingDropDown.jsx

Resolves https://github.com/adaptlearning/adapt-contrib-matching/issues/149
* Converted button / label divs to spans
* Visual fix for div to span conversion

Converted button divs to spans

---

example.json
properties.schema
schema/component.schema.json

#156 
* default instruction text provided

New: Provide default instruction text (fixes #156)

---

README.md
example.json
properties.schema
schema/component.schema.json
templates/matching.jsx

* Adds ariaQuestion, schema & README adjustments to this component
* Fixes #159 
[//]: # (List appropriate steps for testing if needed)
1. Install PR and test in AAT
[//]: # (Mention any other dependencies)

Fix: Add ariaQuestion to component (fixes: 159)

---

templates/matching.jsx
templates/matchingDropDown.jsx

* Fixes #163 
[//]: # (List appropriate steps for testing if needed)
1. Pull down this PR and examine the structure in the output
[//]: # (Mention any other dependencies)

Fix: Normalizing template icons (fixes: #163)

---

README.md
example.json
js/MatchingModel.js
properties.schema
schema/component.schema.json

fixes #148 
* Added `_isRandomQuestionOrder` to display the items in a random order as well as or instead of randomising the item options

New: Added _isRandomQuestionOrder

---

test/e2e/matching.cy.js

Fix: Moved striphtml function outside loop (fixes #185)

---

templates/matching.jsx

#188 
* role added to component__widget div (fixes #188)
References:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role
- https://github.com/adaptlearning/adapt-contrib-mcq/blob/652de564338f5e0a2181d3f5f51c17d111cae998/templates/mcq.jsx#L40

Fix: role added to component__widget div (fixes #188)

---

.github/workflows/releases.yml

* Upgrading the semantic release packages to avoid deprecation warning

Fix: Upgrading the semantic release packages to avoid deprecation warning

---

templates/matching.jsx
templates/matchingDropDown.jsx

* Labeled the Matching dropdown buttons with the match item text using `aria-labelledby`

Update: Added Dropdown labeling (refs #147)

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md

Fixes https://github.com/adaptlearning/adapt-contrib-matching/issues/200
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template

Chore: Add support for new issue experience (fixes #200)

---

bower.json
package-lock.json
package.json

#204 
Part of - https://github.com/adaptlearning/adapt_framework/issues/3698
* package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #204)

Update: package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #204)
