adaptlearning/adapt-contrib-matching

less/matching.less

Note: Firefox v35+ supports [`-moz-appearance: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance) so we'll be able to add this once the [ESR life cycle](https://www.mozilla.org/en-US/firefox/organizations/faq) updates in August.

Reduce impact of ABU-993

---

js/adapt-contrib-matching.js

Fix the following issue: When component is randomised, answer a matching question correctly, close the course, reopen the course, you will find the matching question is set a incorrect.

Fix issue #82 #83 when randomised

---

README.md
properties.schema

README.md: correct entry for `_isRandom` as `false` is the default not `true`
properties.schema: amend to reflect that `_incorrect.notFinal` and all `_partlyCorrect` feedbacks are optional

amends to properties.schema and README

---

README.md
bower.json
example.json
js/adapt-contrib-matching.js
less/matching.less
properties.schema
templates/matching.hbs

Avoids adding correctness classes to items if `_canShowMarking` is false.
Please only merge once the new version of the framework has been released (v2.0.11).
Original issue: adaptlearning/adapt_framework#1046.

Hook into _canShowMarking

---

js/adapt-contrib-matching.js

during `selectValue`, fixes [1503](https://github.com/adaptlearning/adapt_framework/issues/1503)

ensure leading/trailing spaces are stripped from option text

---

js/adapt-contrib-matching.js
less/matching.less
templates/matching.hbs

fixes [#1530](https://github.com/adaptlearning/adapt_framework/issues/1530)
This is now what you see if you don't select all the options before clicking submit
Tested in Chrome, Firefox, Safari for iOS (10), IE8, IE11, Edge ~~and Bono~~

improvements to error handling for when user hasn't selected all the options

---

js/adapt-contrib-matching.js
less/matching.less
templates/matching.hbs

this means that the 'Please select an option' text now no longer needs to appear in the matching dropdown when open, leading to a cleaner looking UI and more room for answer options.
Previous version:
New 'placeholder' version:
I have tested this in Firefox, Edge, Chrome, iOS9 (iPad), iOS10 (iPhone) & IE11.
I don't have access to an Android device but have tested it in Chrome using the device emulator in the dev tools.
I even tested it in IE8 (I was working on #108 at the same time) and - even though Select2 [says it only supports placeholders in IE8 & 9 with a polyfill](https://select2.github.io/examples.html#placeholders), it seemed to work fine for me... not particularly suggesting we need to release this for IE8/9 though!

adds support for the 'placeholder' feature of select2

---

js/adapt-contrib-matching.js

https://github.com/adaptlearning/adapt_framework/issues/1889
1. Add a matching to the bottom of a scrolling page or before a trickle.
2. Add enough options to the last dropdown in the matching, so that it will run off the page - 5/6 options should do.
3. Scroll down to the matching and open the last dropdown
With the fix: The dropdown will appear above the control flowing upwards
Without the fix: The dropdown will appear beneath the control, flowing off the screen

issue/1889: drop down appears above page bottom

---

js/adapt-contrib-matching.js

This is required in preparation for xAPI support.

Resolves #1710, adds getInteractionObject() function

---

js/adapt-contrib-matching.js

this component is no longer compatible with older versions of the Adapt Framework, making this code redundant
resolves https://github.com/adaptlearning/adapt_framework/issues/2584

remove code that was only needed for backwards-compatibility

---

templates/matching.jsx

Fixes #154 
Adds aria-labels of Correct or Incorrect to the tick and cross icons
1. Complete a Matching component with a mix of correct and incorrect responses
2. Toggle between Show Correct Answer and Show My Answer
3. With a screenreader, tab up to where each answer is shown and then to the tick/cross icon.
Relates to https://github.com/adaptlearning/adapt_framework/issues/2241

Fix: Add correct +/ incorrect aria labels to ticks and crosses (fixes #154)

---

templates/matchingDropDown.jsx

Fixes #161 
* u-no-select class added to dropdown item text #161 
[//]: # (List appropriate steps for testing if needed)
1. Attempt to click and drag over item text
2. Ensure text can't be highlighted and instead item is selected as expected
[//]: # (Mention any other dependencies)

Fix: u-no-select class added to dropdown item text (fixes #161)

---

templates/matching.jsx
templates/matchingDropDown.jsx

Fixes https://github.com/adaptlearning/adapt-contrib-matching/issues/173
To support the use of [a11y_alt_text](https://github.com/adaptlearning/adapt-contrib-core/commit/a92c7ffdb431bdf126e080c009b3b9c324642755) helper tag.
Add `a11y_alt_text` helper to Matching item `text` e.g. `{{a11y_alt_text '$5bn' 'five billion dollars'}}`.
In your course, go to the Matching item and '$5bn' should be displayed.
Using the browser devtools, inspect '$5bn' and the helper should have split out the on screen text and a11y text e.g.
`<span aria-hidden="true">$5bn</span><span class="aria-label">five billion dollars</span>`

Fix: compile item text (fixes #173)

---

example.json

Prevent placeholder text being copied over and left in accessible courses. Property description is noted in README and schema help/description for reference.
Fixes https://github.com/adaptlearning/adapt-contrib-matching/issues/175
Missing `ariaQuestion` property added to [wiki](https://github.com/adaptlearning/adapt_framework/wiki/Core-model-attributes/_edit#question-model-attributes).

Update: Remove ariaQuestion placeholder text (fixes #175)

---

test/e2e/matching.cy.js

Chore: e2e tests on matching component (Issue/181)

---

.github/pull_request_template.md
README.md
properties.schema
schema/component.schema.json

Fixes #183 
* Adds missing properties `_allowOnlyUniqueAnswers` and `_hasItemScoring` to _README.md_ and V1 schemas.
* Minor updates to documentation and help text

Fix: Add missing properties _allowOnlyUniqueAnswers and _hasItemScoring (fixes #183)

---

templates/matching.jsx
templates/matchingDropDown.jsx

#190 
* aria-labelledby added to matching dropdown to read out dropdown label/question (fixes #190)

Fix: aria-labelledby added to matching dropdown to read out dropdown label/question (fixes #190)

---

less/dropdown.less

Fixes https://github.com/adaptlearning/adapt-contrib-matching/issues/194
* Focus outline should inherit from browser/OS for consistency with other focusable elements in Adapt. PR removes the outline style that prevents this.

Fix: restore dropdown btn focus outline (fixes #194)

---

README.md
example.json
js/MatchingModel.js
properties.schema
schema/component.schema.json
schema/course.schema.json
templates/matching.jsx

part of https://github.com/adaptlearning/adapt_framework/issues/3597
Allows option `_canShowCorrectness` instead of  `_canShowModelAnswer`, to replace the associated toggle button and display correctness directly on the component.
* Added support for `_canShowCorrectness`
* Show a comma separated list of correct options when `_canShowCorrectness true`
* `.show-correctness` widget class appended for consistency with other question components. Note, there's no associated styling currently.
* Default prefix text added for the correct options. `correctAnswerPrefix` and `correctAnswersPrefix` added to support both single and multiple correct answers. For now this just exists in course `_globals` but could later add a component level override if needed. Or move these to Core if shared across …

New: Added support for _canShowCorrectness

---

templates/matching.jsx
templates/matchingDropDown.jsx

fixes #147
* Added role, aria-controls and relevant id

Fix: a11y combobox attributes (fixes #147)

---

migrations/v2.js
migrations/v3.js
migrations/v4.js
migrations/v6.js
migrations/v7.js

Fix #201 
Part of https://github.com/adaptlearning/adapt_framework/issues/3631
* Migration scripts added to repo 
- Add `_recordInteraction`
- Add `_canShowModelAnswer`
- Add `_canShowMarking`
- Add `_canShowFeedback`
- Add feedback `title`
- Add `_shouldResetAllAnswers` in different [commit](https://github.com/adaptlearning/adapt-contrib-matching/commit/6cf827d0a55f901e8ff2a3689fa22ab32536c216)
Lots of schema changes, but mostly just moving things around
- Update globals `ariaRegion` default
- Update `_isRandom` default to false
- Add globals `ariaCorrectAnswer`
- Add globals `ariaUserAnswer`
- Add `_hasItemScoring`
- Add `_allowOnlyUniqueAnswers`
- Update default `instruction` text
- Add `ariaQuestion` (component)
- Add `_isRandomQuestionOrder`
- Add `_hasItemScoring` (v1 schema only)
- …

New: Migration scripts added to repo (fixes #201)
